spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Eureka ??? ??? ??
          predicates:
            - Path=/api/v1/users/**  # ??? ?? API ??
        - id: task-service
          uri: lb://TASK-SERVICE  # Eureka ??? ??? ??
          predicates:
            - Path=/api/v1/tasks/**  # ?? ?? API ??

server:
  port: 8080  # ?????? ??? ?? ??

# ??? ?? Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
