server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: msa_user
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: msa_task
          uri: lb://task-service
          predicates:
            - Path=/api/v1/tasks/**